### ISSUE TITLE
Fix random crashing

### ISSUE THREAD

**Issue by clman94** [clman94/Wolf-Gang-Engine#17]
This issue only happens on a few PCs without any obvious cause.

On one known PC, the crash seems to occur approximately every 5 minutes. This could be the cause of a memory leak and/or timers overflowing.

**Comment by BK1603** [comment]
New to GitHub,
Can I try solving this or the other open issues mentioned on the repo?

**Comment by clman94** [comment]
Fork and do what you like. This issue has been open for a while and with the many changes that have been happening, I'm not sure if this is even an issue anymore :).

**Comment by clman94** [comment]
The issue has finally been isolated. It turns out that openal doesn't agree well with some drivers on some systems and crashes the process. Either openal or the system's drivers need to be updated for it to work properly (probably).

**Comment by clman94** [comment]
Apparently, the implementation of OpenAL that comes with SFML is horribly buggy. However, in the rewrite of the engine, SFML has been completely removed in favor of more direct handling of OpenAL and OpenGL.
